### ISSUE TITLE
Invalid result https://www.pinterest.com/adopt_me_trader74/

### ISSUE THREAD

**Issue by Chel728** [soxoj/maigret#867] opened 2023-03-15 04:39 UTC
Invalid link: <INSERT LINK HERE>

- [ ] I'm sure that the link leads to "not found" page

**Comment by Chel728** [comment] 2023-03-15 04:40
Оскорбляет мужчин

**Comment by soxoj** [comment] 2023-04-17 08:49
Duplicate of #885

**Closed by soxoj** 2023-04-17 08:49 UTC
