### ISSUE TITLE
Failed to pip install 

### ISSUE THREAD

**Issue by VincentBai-dotcom** [soxoj/maigret#1964] opened 2024-12-13 09:25 UTC
## Checklist

- [yes] I'm reporting a bug in Maigret functionality
- [ ] I've checked for similar bug reports including closed ones
- [ ] I've checked for pull requests that attempt to fix this bug

## Description

Info about Maigret version you are running and environment (`--version`, operation system, ISP provider):
newest version of Maigret, python 3.11.2

How to reproduce this bug (commandline options / conditions):
<INSERT EXAMPLE OF CLI COMMAND HERE>
pip3 install maigret

<DESCRIPTION>
Failed to install maigret

<ATTACH LOG FILE>
Collecting maigret
  Using cached maigret-0.4.4-py3-none-any.whl.metadata (6.8 kB)
Collecting aiodns==3.0.0 (from maigret)
  Using cached aiodns-3.0.0-py3-none-any.whl.metadata (3.5 kB)
Collecting aiohttp==3.8.1 (from maigret)
  Using cached aiohttp-3.8.1.tar.gz (7.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting aiohttp-socks==0.7.1 (from maigret)
  Using cached aiohttp_socks-0.7.1-py3-none-any.whl.metadata (3.1 kB)
Collecting arabic-reshaper==2.1.3 (from maigret)
  Using cached arabic_reshaper-2.1.3-py3-none-any.whl.metadata (12 kB)
WARNING: Ignoring version 2.1.3 of arabic-reshaper since it has invalid metadata:
Requested arabic-reshaper==2.1.3 from https://files.pythonhosted.org/packages/47/27/7b9b824f5342d8ee180027333f2e15842ea36f5bc2d3d24a4e6bb31fb596/arabic_reshaper-2.1.3-py3-none-any.whl (from maigret) has invalid metadata: Expected matching RIGHT_PARENTHESIS for LEFT_PARENTHESIS, after version specifier
    fonttools (>=3.0<4.0) ; (python_version < "3") and extra == 'with-fonttools'
              ~~~~~~^
Please use pip<24.1 if you need to use this version.
INFO: pip is looking at multiple versions of maigret to determine which version is compatible with other requirements. This could take a while.
Collecting maigret
  Using cached maigret-0.4.3-py3-none-any.whl.metadata (6.8 kB)
Collecting arabic-reshaper==2.1.3 (from maigret)
  Using cached arabic_reshaper-2.1.3-py3-none-any.whl.metadata (12 kB)
WARNING: Ignoring version 2.1.3 of arabic-reshaper since it has invalid metadata:
Requested arabic-reshaper==2.1.3 from https://files.pythonhosted.org/packages/47/27/7b9b824f5342d8ee180027333f2e15842ea36f5bc2d3d24a4e6bb31fb596/arabic_reshaper-2.1.3-py3-none-any.whl (from maigret) has invalid metadata: Expected matching RIGHT_PARENTHESIS for LEFT_PARENTHESIS, after version specifier
    fonttools (>=3.0<4.0) ; (python_version < "3") and extra == 'with-fonttools'
              ~~~~~~^
Please use pip<24.1 if you need to use this version.
Collecting maigret
  Using cached maigret-0.4.2-py3-none-any.whl.metadata (6.8 kB)
Collecting arabic-reshaper==2.1.3 (from maigret)
  Using cached arabic_reshaper-2.1.3-py3-none-any.whl.metadata (12 kB)
WARNING: Ignoring version 2.1.3 of arabic-reshaper since it has invalid metadata:
Requested arabic-reshaper==2.1.3 from https://files.pythonhosted.org/packages/47/27/7b9b824f5342d8ee180027333f2e15842ea36f5bc2d3d24a4e6bb31fb596/arabic_reshaper-2.1.3-py3-none-any.whl (from maigret) has invalid metadata: Expected matching RIGHT_PARENTHESIS for LEFT_PARENTHESIS, after version specifier
    fonttools (>=3.0<4.0) ; (python_version < "3") and extra == 'with-fonttools'
              ~~~~~~^
Please use pip<24.1 if you need to use this version.
Collecting maigret
  Using cached maigret-0.4.1-py3-none-any.whl.metadata (6.7 kB)
Collecting arabic-reshaper==2.1.3 (from maigret)
  Using cached arabic_reshaper-2.1.3-py3-none-any.whl.metadata (12 kB)
WARNING: Ignoring version 2.1.3 of arabic-reshaper since it has invalid metadata:
Requested arabic-reshaper==2.1.3 from https://files.pythonhosted.org/packages/47/27/7b9b824f5342d8ee180027333f2e15842ea36f5bc2d3d24a4e6bb31fb596/arabic_reshaper-2.1.3-py3-none-any.whl (from maigret) has invalid metadata: Expected matching RIGHT_PARENTHESIS for LEFT_PARENTHESIS, after version specifier
    fonttools (>=3.0<4.0) ; (python_version < "3") and extra == 'with-fonttools'
              ~~~~~~^
Please use pip<24.1 if you need to use this version.
Collecting maigret
  Using cached maigret-0.4.0-py3-none-any.whl.metadata (6.7 kB)
Collecting arabic-reshaper==2.1.3 (from maigret)
  Using cached arabic_reshaper-2.1.3-py3-none-any.whl.metadata (12 kB)
WARNING: Ignoring version 2.1.3 of arabic-reshaper since it has invalid metadata:
Requested arabic-reshaper==2.1.3 from https://files.pythonhosted.org/packages/47/27/7b9b824f5342d8ee180027333f2e15842ea36f5bc2d3d24a4e6bb31fb596/arabic_reshaper-2.1.3-py3-none-any.whl (from maigret) has invalid metadata: Expected matching RIGHT_PARENTHESIS for LEFT_PARENTHESIS, after version specifier
    fonttools (>=3.0<4.0) ; (python_version < "3") and extra == 'with-fonttools'
              ~~~~~~^
Please use pip<24.1 if you need to use this version.
Collecting maigret
  Using cached maigret-0.3.1-py3-none-any.whl.metadata (6.7 kB)
Collecting aiohttp==3.7.4 (from maigret)
  Using cached aiohttp-3.7.4.tar.gz (1.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting aiohttp-socks==0.5.5 (from maigret)
  Using cached aiohttp_socks-0.5.5-py3-none-any.whl.metadata (2.9 kB)
Collecting arabic-reshaper==2.1.1 (from maigret)
  Using cached arabic_reshaper-2.1.1.tar.gz (18 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      /private/var/folders/_3/dm69bll529x6gpqs801226kw0000gn/T/pip-build-env-8qqmjmbr/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py:261: UserWarning: Unknown distribution option: 'test_suite'
        warnings.warn(msg)
      error in arabic_reshaper setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by josermarinr** [comment] 2024-12-13 09:47
same error with python 3.11.5 in macOS 15.1.1 

```
pip install maigret
Collecting maigret
  Using cached maigret-0.4.4-py3-none-any.whl.metadata (6.8 kB)
Collecting aiodns==3.0.0 (from maigret)
  Using cached aiodns-3.0.0-py3-none-any.whl.metadata (3.5 kB)
Collecting aiohttp==3.8.1 (from maigret)
  Using cached aiohttp-3.8.1.tar.gz (7.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting aiohttp-socks==0.7.1 (from maigret)
  Using cached aiohttp_socks-0.7.1-py3-none-any.whl.metadata (3.1 kB)
Collecting arabic-reshaper==2.1.3 (from maigret)
  Using cached arabic_reshaper-2.1.3-py3-none-any.whl.metadata (12 kB)
WARNING: Ignoring version 2.1.3 of arabic-reshaper since it has invalid metadata:
Requested arabic-reshaper==2.1.3 from https://files.pythonhosted.org/packages/47/27/7b9b824f5342d8ee180027333f2e15842ea36f5bc2d3d24a4e6bb31fb596/arabic_reshaper-2.1.3-py3-none-any.whl (from maigret) has invalid metadata: Expected matching RIGHT_PARENTHESIS for LEFT_PARENTHESIS, after version specifier
    fonttools (>=3.0<4.0) ; (python_version < "3") and extra == 'with-fonttools'
              ~~~~~~^
Please use pip<24.1 if you need to use this version.
INFO: pip is looking at multiple versions of maigret to determine which version is compatible with other requirements. This could take a while.
Collecting maigret
  Using cached maigret-0.4.3-py3-none-any.whl.metadata (6.8 kB)
Collecting arabic-reshaper==2.1.3 (from maigret)
  Using cached arabic_reshaper-2.1.3-py3-none-any.whl.metadata (12 kB)
WARNING: Ignoring version 2.1.3 of arabic-reshaper since it has invalid metadata:
Requested arabic-reshaper==2.1.3 from https://files.pythonhosted.org/packages/47/27/7b9b824f5342d8ee180027333f2e15842ea36f5bc2d3d24a4e6bb31fb596/arabic_reshaper-2.1.3-py3-none-any.whl (from maigret) has invalid metadata: Expected matching RIGHT_PARENTHESIS for LEFT_PARENTHESIS, after version specifier
    fonttools (>=3.0<4.0) ; (python_version < "3") and extra == 'with-fonttools'
              ~~~~~~^
Please use pip<24.1 if you need to use this version.
Collecting maigret
  Using cached maigret-0.4.2-py3-none-any.whl.metadata (6.8 kB)
Collecting arabic-reshaper==2.1.3 (from maigret)
  Using cached arabic_reshaper-2.1.3-py3-none-any.whl.metadata (12 kB)
WARNING: Ignoring version 2.1.3 of arabic-reshaper since it has invalid metadata:
Requested arabic-reshaper==2.1.3 from https://files.pythonhosted.org/packages/47/27/7b9b824f5342d8ee180027333f2e15842ea36f5bc2d3d24a4e6bb31fb596/arabic_reshaper-2.1.3-py3-none-any.whl (from maigret) has invalid metadata: Expected matching RIGHT_PARENTHESIS for LEFT_PARENTHESIS, after version specifier
    fonttools (>=3.0<4.0) ; (python_version < "3") and extra == 'with-fonttools'
              ~~~~~~^
Please use pip<24.1 if you need to use this version.
Collecting maigret
  Using cached maigret-0.4.1-py3-none-any.whl.metadata (6.7 kB)
Collecting arabic-reshaper==2.1.3 (from maigret)
  Using cached arabic_reshaper-2.1.3-py3-none-any.whl.metadata (12 kB)
WARNING: Ignoring version 2.1.3 of arabic-reshaper since it has invalid metadata:
Requested arabic-reshaper==2.1.3 from https://files.pythonhosted.org/packages/47/27/7b9b824f5342d8ee180027333f2e15842ea36f5bc2d3d24a4e6bb31fb596/arabic_reshaper-2.1.3-py3-none-any.whl (from maigret) has invalid metadata: Expected matching RIGHT_PARENTHESIS for LEFT_PARENTHESIS, after version specifier
    fonttools (>=3.0<4.0) ; (python_version < "3") and extra == 'with-fonttools'
              ~~~~~~^
Please use pip<24.1 if you need to use this version.
Collecting maigret
  Using cached maigret-0.4.0-py3-none-any.whl.metadata (6.7 kB)
Collecting arabic-reshaper==2.1.3 (from maigret)
  Using cached arabic_reshaper-2.1.3-py3-none-any.whl.metadata (12 kB)
WARNING: Ignoring version 2.1.3 of arabic-reshaper since it has invalid metadata:
Requested arabic-reshaper==2.1.3 from https://files.pythonhosted.org/packages/47/27/7b9b824f5342d8ee180027333f2e15842ea36f5bc2d3d24a4e6bb31fb596/arabic_reshaper-2.1.3-py3-none-any.whl (from maigret) has invalid metadata: Expected matching RIGHT_PARENTHESIS for LEFT_PARENTHESIS, after version specifier
    fonttools (>=3.0<4.0) ; (python_version < "3") and extra == 'with-fonttools'
              ~~~~~~^
Please use pip<24.1 if you need to use this version.
Collecting maigret
  Using cached maigret-0.3.1-py3-none-any.whl.metadata (6.7 kB)
Collecting aiohttp==3.7.4 (from maigret)
  Using cached aiohttp-3.7.4.tar.gz (1.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting aiohttp-socks==0.5.5 (from maigret)
  Using cached aiohttp_socks-0.5.5-py3-none-any.whl.metadata (2.9 kB)
Collecting arabic-reshaper==2.1.1 (from maigret)
  Using cached arabic_reshaper-2.1.1.tar.gz (18 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      /private/var/folders/7t/_dh4970s2hn6bjpnpfxqryzm0000gn/T/pip-build-env-en8vrd1a/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py:261: UserWarning: Unknown distribution option: 'test_suite'
        warnings.warn(msg)
      error in arabic_reshaper setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by soxoj** [comment] 2024-12-13 10:24
Hi guys, thanks. As a temporary measure, I suggest installing Maigret from the repository until I publish the new release in PyPi:

```console
pip install git+https://github.com/soxoj/maigret
```

Closing this issue as a duplicate of #1946.

**Closed by soxoj** 2024-12-13 10:24 UTC
Labels: bug

**Comment by josermarinr** [comment] 2024-12-13 10:39
Thanks @soxoj

**Comment by josermarinr** [comment] 2024-12-13 10:42
Working for me! @soxoj
