### ISSUE TITLE
Invalid result https://www.pinterest.com/s1wet/

### ISSUE THREAD

**Issue by xrcmn** [soxoj/maigret#850] opened 2023-02-10 20:16 UTC
Invalid link: <INSERT LINK HERE>

- [x] I'm sure that the link leads to "not found" page

**Comment by Twis84** [comment] 2023-02-17 12:26
http://actual-porn.org/member.php?username=Popovaanzhela18

**Comment by soxoj** [comment] 2023-04-17 08:49
Duplicate of #885

**Closed by soxoj** 2023-04-17 08:49 UTC
