### ISSUE TITLE
Stuck on last two websites

### ISSUE THREAD

**Issue by maximousblk** [soxoj/maigret#101] opened 2021-04-01 08:38 UTC
When I run maigret on my username with the `-a` option the CLI gets stuck on the last two websites

![Screenshot_20210401-140454_Chrome](https://user-images.githubusercontent.com/28438021/113266806-4d81ea00-92f3-11eb-8997-29b31b8c859e.jpg)

This reduces to getting stuck on one website when I use only top 50 and doesn't happen when using top 30 or less

**Comment by maximousblk** [comment] 2021-04-01 15:21
**Update**: this does not happen when I use `--no-recursion`

**Comment by soxoj** [comment] 2021-04-01 18:13
Thank you, I will study that case. Do I understand correctly that you made a search by your own username?

Also, it would be helpful to see your runtime params: `maigret --version`

**Comment by maximousblk** [comment] 2021-04-01 18:21
Yes I'm testing on my own username (`maximousblk`)

I am using the latest commit (https://github.com/soxoj/maigret/commit/01e20518c12cf540ae59c1050ccc8b6408f5bc3d)

**Comment by soxoj** [comment] 2021-04-01 18:50
I believe this problem is related to #102, looks like there is hanging network connection with some site.
Could you run the search with `--print-not-found --print-errors`, save CLI output to file and attach here (or email me)? 

I'll compare the output with the full list of sites. Most likely a site that will not be listed in the results is causing the problem.

**Comment by maximousblk** [comment] 2021-04-02 03:18
I can no longer reproduce this problem 😞 

Note that, I'm running all these tests in GitHub actions and Google colab so stable internet connection should not be a problem.

**Comment by maximousblk** [comment] 2021-04-02 03:18
I can no longer reproduce this problem 😞 

Note that, I'm running all these tests in GitHub actions and Google colab so stable internet connection should not be a problem.

**Comment by BushidoUK** [comment] 2021-04-03 13:20
Hi, I am getting the same error where Maigret gets stuck at 498/500 or 499/500. 
I am running with the` --no-recursion flag` and when I used `--print-not-found` and `--print-errors` this was the result:
hxxps://i.imgur[.]com/PnGhlCR.png

**Comment by soxoj** [comment] 2021-04-03 15:10
Thank you, @BushidoUK, could you also please report `maigret --version` output?

**Comment by BushidoUK** [comment] 2021-04-03 16:25
@soxoj it was the latest version of maigret, I just cloned it new

**Comment by hrshadhin** [comment] 2021-04-05 13:20
facing same issue.
```
maigret 0.1.18
Socid-extractor:  0.0.16
Aiohttp:  3.7.4
Requests:  2.25.1
Python:  3.8.3
```

**Comment by soxoj** [comment] 2021-04-05 21:31
Guys, it's looks like a mass problem, but I still can't reproduce it. 
Please, do the following:
- report the exact entered command;
- attach as a text file an error traceback after Ctrl+C press;
- write the `maigret --version` output;
- write you ISP (if it's not a secret, of course).

**Comment by mclancy10006** [comment] 2021-04-05 21:42
Same issue here.

maigret 0.1.18
Socid-extractor:  0.0.16
Aiohttp:  3.7.4
Requests:  2.25.1
Python:  3.8.8
ubuntu@petridis
[maigret.txt](https://github.com/soxoj/maigret/files/6260793/maigret.txt)
This is from a co-lo host at Hivelocity (hvvc.us) which peers with Level3

**Comment by soxoj** [comment] 2021-04-08 21:23
Great, thanks, @mclancy10006! 
I see there are no sites in results that have the account you are looking for, and for which Maigret is trying to extract info through [socid-extractor](https://github.com/soxoj/socid-extractor).

I have a theory that lack of processor resources makes the extraction slow down (cause there are many regular expressions under the hood).

Please, run `maigret mclancy10006 --site GitHub -vvv`, interrupt execution with Ctrl+C if it is stuck, and send the output.

Also could you please report your machine configuration (CPU, memory), @mclancy10006 @hrshadhin @BushidoUK @maximousblk?

**Comment by maximousblk** [comment] 2021-04-09 08:44
I have tested it on GitHub Actions and Google Colab so

Actions:
- RAM: 7GB
- CPU: 2 core Xeon

Colab:
- RAM: ~12GB (dynamically allocated)
- CPU: 2 core Xeon

**Comment by soxoj** [comment] 2021-04-11 15:00
Well, looks like my first theory was untenable. I reproduced the problem and make the patch. Please, test it manually, it's located in the branch `async-tasks-timeout`:
```bash
git clone https://github.com/soxoj/maigret && cd maigret
git checkout async-tasks-timeout
./maigret.py john --print-not-found --print-errors
```

**Comment by soxoj** [comment] 2021-04-12 20:02
Merged to master.

**Comment by soxoj** [comment] 2021-04-18 12:08
Hey guys, is the problem still reproducible? I will close the issue if not.

**Comment by maximousblk** [comment] 2021-04-18 17:11
I can't reproduce this after when I opened this issue.


I we can close it and reopen if the problem comes back.?

**Comment by soxoj** [comment] 2021-04-18 18:18
Sure, okay.

**Closed by soxoj** 2021-04-18 18:18 UTC
Labels: bug
