### ISSUE TITLE
Invalid result https://flirtic.ee/lomineqo.evadamu

### ISSUE THREAD

**Issue by sfriga66** [soxoj/maigret#622] opened 2022-09-03 16:51 UTC
Invalid link: <INSERT LINK HERE>

- [x] I'm sure that the link leads to "not found" page

**Comment by soxoj** [comment] 2022-09-11 11:18
Thank you, the problem caused by dot in username. I'll add check for username format to avoid false positive result

**Comment by soxoj** [comment] 2022-09-11 11:24
Fixed in #634

**Closed by soxoj** 2022-09-11 11:24 UTC
